### ISSUE TITLE
A question about `data.txt`

### ISSUE THREAD

**Issue by akdong91** [ekraka/SSnet#3]
Hi

I have a couple of questions about data.txt. This file includes three fields: smile, protein_name, score

1. What is the definition of the score in this file?
2. How did you get the score? Did you calculate it? If you did, can you share how to calculate the score? 

Thanks in advance

**Comment by Niraj288** [comment]
Hi, 

The data.txt was created from humans dataset of protein-ligand interactions. The scores were already annotated there. 1 is high binding and 0 is no binding.

For application of SSnet check SSnet_in_Action. 

Let me know if you have questions.

Thanks
