### ISSUE TITLE
grad model output

### ISSUE THREAD

**Issue by BioLaoXu** [ekraka/SSnet#4]
Dear developers,SSnet is pretty cool tool for docking protein-complexes，traditional docking methods are too slow(auto-dock vina or zdock etc),I have successfully downloaded and deployed your software in centos7，then i test it with two protein pdb files which generate from MODELLER 10.1 ,the to files(Set the txt suffix just for upload github):
[IL2RA.pdb.txt](https://github.com/ekraka/SSnet/files/6897731/IL2RA.pdb.txt)
[IL2RA.smi.txt](https://github.com/ekraka/SSnet/files/6897733/IL2RA.smi.txt)
[IL2.pdb.txt](https://github.com/ekraka/SSnet/files/6897734/IL2.pdb.txt)

the IL2RA.smi.txt file is generage from by Open Babel 3.1.0(obabel -ipdb IL2RA.pdb -osmi -O IL2RA.smi)
The software runs very quickly and successfully with GRAD CAM model，just like bellow:
```
SSnet_linux -t IL2.pdb -l IL2RA.smi -m grad
Using TensorFlow backend.

======================================================================
==       Secondary Structure Based Deep Neural Network Model        ==
==          for Protein-ligand Interaction Prediction :             ==
==                         Code version 1.0                         ==
==                                                                  ==
==    Computational and Theoretical Chemistry Group (CATCO), SMU    ==
==                     Dallas, Texas 75275 USA                      ==
======================================================================


            _|_|_|    _|_|_|                        _|
            _|        _|        _|_|_|    _|_|    _|_|_|_|
            _|_|      _|_|    _|    _|  _|_|_|_|    _|
                _|        _|  _|    _|  _|          _|
            _|_|_|    _|_|_|  _|    _|    _|_|_|      _|_|

If no idea how it works!, include -h as argument


Input parameters: {'-m': 'grad', '-t_dir': '.', '-t': 'IL2.pdb', '-l': 'IL2RA.smi'}
2021-07-29 14:08:54.205471: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2021-07-29 14:08:54.231058: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2900000000 Hz
2021-07-29 14:08:54.242212: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56086700c8c0 executing computations on platform Host. Devices:
2021-07-29 14:08:54.242290: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2021-07-29 14:08:54.249493: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
0
Done!

```
there is just one smile format txt file :results_IL2_IL2RA.txt:
[results_IL2_IL2RA.txt](https://github.com/ekraka/SSnet/files/6898280/results_IL2_IL2RA.txt)
According to the usage document [SSnet_in_Action](https://github.com/ekraka/SSnet/tree/master/SSnet_in_Action), a PDB file should been generated if the GRAD CAM analysis had been performed,  but it is very troublesome and no pdb file is generated.
I tried to convert the results_IL2_IL2RA. txt  file into a PDB file through obabel（obabel -ismi results_IL2_IL2RA.txt -opdb -O IL2_IL2RA.pdb） for visualization, but the 3D coordinate information of atoms was missing in the PDB file
[IL2_IL2RA.pdb.txt](https://github.com/ekraka/SSnet/files/6898430/IL2_IL2RA.pdb.txt)
![image](https://user-images.githubusercontent.com/13416926/127444144-5d5ce90d-132c-4f43-a711-02c8746363f2.png)

May I ask, did this result meet my expectations? What improvements do I need to make to get the correct PDB file? Looking forward to your reply,thanks.

**Comment by BioLaoXu** [comment]
i have tested the official exemple :
```SSnet_linux -t 6M18.pdb -l 'C[C@H](N[C@@H](CCc1ccccc1)C(=O)O)C(=O)N1[C@H](C(=O)O)C[C@H]2CCCC[C@@H]21' -m grad```
The software runs very quickly and successfully with GRAD CAM model,and the 6M18_GRAD.pdb file is generate,i replace 6M18.pdb to my own IL2.pdb file, it's worked,IL2_GRAD.pdb is generated,so I suspect that there is something wrong with the SMI file of the ligand. How should I generate the SMI file of the ligand? In addition, is there any limit on the length of the ligand,thanks.

**Comment by Niraj288** [comment]
> Dear developers,SSnet is pretty cool tool for docking protein-complexes，traditional docking methods are too slow(auto-dock vina or zdock etc),I have successfully downloaded and deployed your software in centos7，then i test it with two protein pdb files which generate from MODELLER 10.1 ,the to files(Set the txt suffix just for upload github):
> [IL2RA.pdb.txt](https://github.com/ekraka/SSnet/files/6897731/IL2RA.pdb.txt)
> [IL2RA.smi.txt](https://github.com/ekraka/SSnet/files/6897733/IL2RA.smi.txt)
> [IL2.pdb.txt](https://github.com/ekraka/SSnet/files/6897734/IL2.pdb.txt)
> 
> the IL2RA.smi.txt file is generage from by Open Babel 3.1.0(obabel -ipdb IL2RA.pdb -osmi -O IL2RA.smi)
> The software runs very quickly and successfully with GRAD CAM model，just like bellow:
> 
> ```
> SSnet_linux -t IL2.pdb -l IL2RA.smi -m grad
> Using TensorFlow backend.
> 
> ======================================================================
> ==       Secondary Structure Based Deep Neural Network Model        ==
> ==          for Protein-ligand Interaction Prediction :             ==
> ==                         Code version 1.0                         ==
> ==                                                                  ==
> ==    Computational and Theoretical Chemistry Group (CATCO), SMU    ==
> ==                     Dallas, Texas 75275 USA                      ==
> ======================================================================
> 
> 
>             _|_|_|    _|_|_|                        _|
>             _|        _|        _|_|_|    _|_|    _|_|_|_|
>             _|_|      _|_|    _|    _|  _|_|_|_|    _|
>                 _|        _|  _|    _|  _|          _|
>             _|_|_|    _|_|_|  _|    _|    _|_|_|      _|_|
> 
> If no idea how it works!, include -h as argument
> 
> 
> Input parameters: {'-m': 'grad', '-t_dir': '.', '-t': 'IL2.pdb', '-l': 'IL2RA.smi'}
> 2021-07-29 14:08:54.205471: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
> To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
> 2021-07-29 14:08:54.231058: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2900000000 Hz
> 2021-07-29 14:08:54.242212: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56086700c8c0 executing computations on platform Host. Devices:
> 2021-07-29 14:08:54.242290: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
> 2021-07-29 14:08:54.249493: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
> 0
> Done!
> ```
> 
> there is just one smile format txt file :results_IL2_IL2RA.txt:
> [results_IL2_IL2RA.txt](https://github.com/ekraka/SSnet/files/6898280/results_IL2_IL2RA.txt)
> According to the usage document [SSnet_in_Action](https://github.com/ekraka/SSnet/tree/master/SSnet_in_Action), a PDB file should been generated if the GRAD CAM analysis had been performed, but it is very troublesome and no pdb file is generated.
> I tried to convert the results_IL2_IL2RA. txt file into a PDB file through obabel（obabel -ismi results_IL2_IL2RA.txt -opdb -O IL2_IL2RA.pdb） for visualization, but the 3D coordinate information of atoms was missing in the PDB file
> [IL2_IL2RA.pdb.txt](https://github.com/ekraka/SSnet/files/6898430/IL2_IL2RA.pdb.txt)
> ![image](https://user-images.githubusercontent.com/13416926/127444144-5d5ce90d-132c-4f43-a711-02c8746363f2.png)
> 
> May I ask, did this result meet my expectations? What improvements do I need to make to get the correct PDB file? Looking forward to your reply,thanks.

Hi, Thanks for the questions. For now GRAD-CAM is limited to one ligand and one protein at a time (since it takes extra time to fit the gradients). What I mean is you have to provide the target as a pdb file (-t IL2.pdb) and a single ligand (-l 'O' ) (SMILES for water). As an example, the whole code would look like:

        SSnet_linux -t IL2.pdb -l 'CCCCCC1=CC(=C2C3C=C(CCC3C(OC2=C1)(C)C)C)O' -m grad

This will generate a pdb file that you can open in any visualization tool and color them with b-factor

**Comment by Niraj288** [comment]
> i have tested the official exemple :
> `SSnet_linux -t 6M18.pdb -l 'C[C@H](N[C@@H](CCc1ccccc1)C(=O)O)C(=O)N1[C@H](C(=O)O)C[C@H]2CCCC[C@@H]21' -m grad`
> The software runs very quickly and successfully with GRAD CAM model,and the 6M18_GRAD.pdb file is generate,i replace 6M18.pdb to my own IL2.pdb file, it's worked,IL2_GRAD.pdb is generated,so I suspect that there is something wrong with the SMI file of the ligand. How should I generate the SMI file of the ligand? In addition, is there any limit on the length of the ligand,thanks.

As I mentioned, GRAD-CAM only works with a single ligand provided as SMILES. I would like to note that GRAD-CAM is ligand specific! Thus, different ligands may give different results.

**Comment by Niraj288** [comment]
Solved
